channel#basic_cancel
cloudamqp/amqp-client.cr pull request #16
Opened 2020-09-02 11:39 UTC by antondalgren

Subscriber should still process the messages it's assigned to

> This method cancels a consumer. This does not affect already delivered messages, but it does mean the server will not send any more messages for that consumer. The client may receive an arbitrary number of messages in between sending the cancel method and receiving the cancel-ok reply. https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.cancel

Co-authored-by: Anders Bälter <anders@84codes.com>

2020-09-02 22:07 UTC, carlhoerberg requested changes
Ok, but why don't we just leave the consumer as it is? No need to delete it at all, msgs might come in at any point in time after we've sent the Cancel frame. Will only be a memory problem if users have a high churn rate of consumers. The new Hash you introduced will also cause high memory use at high churn rate.  (FYI Fiber.yield is equivalent to sleep 0)

2020-09-03 15:24 UTC, carlhoerberg commented
or better yet, send Cancel with no_wait = false and then on CancelOk from the server we delete the consumer.

2020-09-03 15:40 UTC, baelter commented
> or better yet, send Cancel with no_wait = false and then on CancelOk from the server we delete the consumer. 

If we have high prefetch there might still be unhandeld messages when we get CancelOk

2020-09-03 16:25 UTC, carlhoerberg commented
Ok, but then maybe send a special message on the @deliveries channel in Channel, when a CancelOk comes in. So that the delivery loop method deletes the callback function

2020-09-03 18:37 UTC, carlhoerberg commented
currently all messages to a channel are processed on a single fiber. wondering if would be a better idea to have a fiber per consumer instead. and then we close that fiber when we get the CancelOk

2020-09-04 07:55 UTC, antondalgren commented
Your changes looks good to me! @carlhoerberg  🚀 🎉

2020-09-04 08:02 UTC, merged