Examples
cloudamqp/amqp-client.cr pull request #19
Opened 2020-11-25 00:00 UTC by annieblomgren

Examples inspired by tutorials for RabbitMQ https://www.rabbitmq.com/getstarted.html

2020-11-25 15:18 UTC, baelter requested changes
Use 2 space indentation. I can help you configure your editor to do this manually. Which one are you using?

2020-11-25 15:18 UTC, baelter commented on examples/HelloWorld_publisher.cr
> +      puts "Sent: Hello World!"
```suggestion
     puts "Sent: Hello World!"
```

2020-11-25 15:18 UTC, baelter commented on examples/PublishSubscribe_consumer.cr
> +      puts "Waiting for logs. To exit press CTRL+C"
```suggestion
     puts "Waiting for logs. To exit press CTRL+C"
```

2020-11-25 15:18 UTC, baelter commented on examples/PublishSubscribe_consumer.cr
> +      msg.ack
```suggestion
       puts "Received: #{msg.body_io.to_s}"
       msg.ack
```

2020-11-25 15:18 UTC, baelter commented on examples/PublishSubscribe_consumer.cr
> +      puts "Done"
```suggestion
     puts "Done"
```

2020-11-25 15:18 UTC, baelter commented on examples/PublishSubscribe_publisher.cr
> +   ch.basic_publish msg, exchange: "logs"
```suggestion
     e = ch.exchange_declare("logs", type: "fanout")
     q = ch.queue
     q.bind exchange: "logs", routing_key: ""
     msg = ARGV.empty? ? "Hello World!" : ARGV.join(' ')
     ch.basic_publish msg, exchange: "logs"
```

2020-11-25 15:18 UTC, baelter commented on examples/Routing_consumer.cr
> +     q.bind exchange: "direct_logs", routing_key: severity
```suggestion
AMQP::Client.start("amqps://user:password@hostname/vhost") do |c|
   c.channel do |ch|
     q = ch.queue
     ARGV.each do |severity|
       q.bind exchange: "direct_logs", routing_key: severity
```

2020-11-25 15:18 UTC, baelter commented on examples/Routing_consumer.cr
> +      puts "Waiting for logs. To exit press CTRL+C"
```suggestion
     puts "Waiting for logs. To exit press CTRL+C"
```

2020-11-25 15:18 UTC, baelter commented on examples/Routing_consumer.cr
> +      puts "Done"
```suggestion
       puts "Received: #{msg.body_io.to_s}"
       msg.ack
       puts "Done"
```

2020-11-25 15:18 UTC, baelter commented on examples/Routing_publisher.cr
> +   ch.basic_publish msg, exchange: "direct_logs", routing_key: severity
```suggestion
     e = ch.exchange_declare("direct_logs", type: "direct")
     q = ch.queue
     severity = ARGV.shift || "info"
     q.bind exchange: "direct_logs", routing_key: severity
     msg = ARGV.empty? ? "Hello World!" : ARGV.join(' ')
     ch.basic_publish msg, exchange: "direct_logs", routing_key: severity
```

2020-11-25 15:18 UTC, baelter commented on examples/Topics_consumer.cr
> +     q.bind exchange: "topic_animals", routing_key: animals
```suggestion
       q.bind exchange: "topic_animals", routing_key: animals
```

2020-11-25 15:18 UTC, baelter commented on examples/Topics_consumer.cr
> +      puts "Waiting for logs. To exit press CTRL+C"
```suggestion
     puts "Waiting for logs. To exit press CTRL+C"
```

2020-11-25 15:18 UTC, baelter commented on examples/Topics_consumer.cr
> +      puts "Done"
```suggestion
       puts "Received: #{msg.body_io.to_s}"
       msg.ack
       puts "Done"
```

2020-11-25 15:18 UTC, baelter commented on examples/Topics_publisher.cr
> +   end
```suggestion
  c.channel do |ch|
    e = ch.exchange_declare("topic_animals", type: "topic")
    q = ch.queue
    animals = ARGV.shift || "anonymous.info"
    q.bind exchange: "topic_animals", routing_key: animals
    msg = ARGV.empty? ? "Hello World!" : ARGV.join(' ')
    ch.basic_publish msg, exchange: "topic_animals", routing_key: animals
    puts "Sent: #{msg}"
  end
```

2020-11-25 15:18 UTC, baelter commented on examples/WorkQueues_consumer.cr
> +    end
```suggestion
  c.channel do |ch|
    q = ch.queue("hello")
    ch.prefetch(count: 1)
    puts "Waiting for messages. To exit press CTRL+C"
    q.subscribe(no_ack: false, block: true) do |msg|
      puts "Received: #{msg.body_io.to_s}"
      msg.ack
      sleep msg.body_io.to_s.count('.')
      puts "Done"
    end
```

2020-11-25 15:18 UTC, baelter commented on examples/WorkQueues_publisher.cr
> +   end
```suggestion
  c.channel do |ch|
    q = ch.queue_declare(name: "hello", durable: true)
    ch.queue_bind("hello", "amq.direct", "hello")
    msg = ARGV.empty? ? "Hello World!" : ARGV.join(' ')
    ch.basic_publish msg, exchange: "amq.direct", routing_key: "hello", props: AMQP::Client::Properties.new(delivery_mode: 2)
      puts "Sent: #{msg}"
    end
```

2020-11-25 20:54 UTC, annieblomgren reviewed
Thanks Anders, looks good to me!

2020-11-26 15:25 UTC, baelter commented
> Thanks Anders, looks good to me!

Tricky go get indentation right in the github ui. Use your newly configured vscode to re-indent this code and make another commit.

2020-12-03 09:23 UTC, carlhoerberg requested changes

2020-12-03 09:23 UTC, carlhoerberg commented on examples/PublishSubscribe_publisher.cr
> +    ch.basic_publish msg, exchange: "logs"
```suggestion
    e.publish msg
```

2020-12-03 09:23 UTC, carlhoerberg commented on examples/Routing_consumer.cr
> +      q.bind exchange: "direct_logs", routing_key: severity
that exchange isn't declared. if it doesn't exists this will throw an error

2020-12-03 09:23 UTC, carlhoerberg commented on examples/Routing_publisher.cr
> +    ch.basic_publish msg, exchange: "direct_logs", routing_key: severity
```suggestion
    e.publish msg, routing_key: severity
```

2020-12-03 09:23 UTC, carlhoerberg commented on examples/WorkQueues_publisher.cr
> +    q = ch.queue_declare(name: "hello", durable: true)
the return value from `queue_declare` is never used 
```suggestion
    ch.queue_declare(name: "hello", durable: true)
```

2020-12-03 09:23 UTC, carlhoerberg commented on examples/HelloWorld_consumer.cr
> +    q.subscribe(tag: "helloconsumer", block: true) do |msg|
why declare a custom tag? 
```suggestion
    q.subscribe(block: true) do |msg|
```

2020-12-03 09:23 UTC, carlhoerberg commented on examples/HelloWorld_publisher.cr
> +    q.publish "Hello World!"
`publish_confirm` is the safe method to use, makes sure that the server acknowledge that it recivied the message. It's very much slower when publshing thousnads per second, but i think we should promote the safety by default. 
```suggestion
    q.publish_confirm "Hello World!"
```

2020-12-03 09:23 UTC, carlhoerberg commented on examples/PublishSubscribe_consumer.cr
> +    q.bind exchange: "logs", routing_key: ""
`logs` exchange has to be declared before trying to bind to it

2020-12-03 09:23 UTC, carlhoerberg commented on examples/PublishSubscribe_publisher.cr
> +    e = ch.exchange_declare("logs", type: "fanout")
```suggestion
    e = ch.exchange("logs", type: "fanout")
```

2020-12-08 13:01 UTC, baelter reviewed
What carl said

2021-01-26 23:07 UTC, carlhoerberg commented
ping @annieblomgren

2021-02-16 03:26 UTC, annieblomgren commented
accept changes

2021-02-16 03:26 UTC, merged